---

- name: Create bridge network
  become: true
  nmcli:
    conn_name: "{{ item }}"
    ifname: "{{ item }}"
    type: bridge
    ip4: "{{ kvm_network_bridges[item]['ip4'] }}"
    gw4: "{{ kvm_network_bridges[item]['gw4'] }}"
    stp: no
    autoconnect: yes
    state: present

- name: Create bridge network
  become: true
  shell: nmcli con mod "{{ item }}" ipv4.dns "{{ kvm_network_bridges[item]['dns4'] | join(',') }}"

- name: Create bridge network
  become: true
  shell: nmcli con up "{{ item }}"

- name: Check if slave is created
  shell: nmcli con show "{{ item }}-slave"
  failed_when: slave_exist.rc not in [0, 10]
  register: slave_exist

- name: Create bridge slave
  become: true
  shell: nmcli con add type ethernet con-name "{{ item }}-slave" ifname "{{ kvm_network_bridges[item]['slave'] }}" master "{{ item }}" autoconnect yes
  when: slave_exist.rc == 10

- name: Stop the ethernet interface
  become: true
  shell: nmcli con down "{{ kvm_network_bridges[item]['slave'] }}"
  failed_when: slave_exist.rc not in [0, 10]
