---

- name: Create bridge networks
  become: true
  include_tasks: bridge.yml
  with_items: "{{ kvm_network_bridges }}"

- name: Create virtual networks
  become: true
  include_tasks: virtual-net.yml
  with_items: "{{ kvm_virtual_networks }}"
