---

- name: facts
  become: true
  virt_pool:
    command: facts

- name: Define stogage pools
  become: true
  virt_pool:
    name: "{{ item }}"
    command: define
    xml: "{{ lookup('template', 'pool.xml.j2') }}"
  with_items: "{{ kvm_pools }}"
  when: ansible_libvirt_pools.get(item, {}).get('state', "") == ""

- name: Build stogage pools
  become: true
  virt_pool:
    name: "{{ item }}"
    command: build
    xml: "{{ lookup('template', 'pool.xml.j2') }}"
  with_items: "{{ kvm_pools }}"
  when: ansible_libvirt_pools.get(item, {}).get('state', "") == ""

- name: Change the stogage pools state to active
  become: true
  virt_pool:
    name: "{{ item }}"
    state: active
  with_items: "{{ kvm_pools }}"

- name: Ensure the stogage pools are started on boot
  become: true
  virt_pool:
    name: "{{ item }}"
    autostart: yes
  with_items: "{{ kvm_pools }}"
